### ISSUE TITLE
 PixelFaramitaLuminousPolymerization的一些小bug

### ISSUE THREAD

**Issue by As12689** [LazuliKao/PixelFaramitaLuminousPolymerizationRes#1]
PixelFaramitaLuminousPolymerization這個真的是很好的插件
不過雖然功能尚未全開，尚屬測試版，不過真的已經很好用了，但提供一些使用上的心得
領地插件部分:op權限目前似乎還沒辦法完全控制，即便點選改權限了，但似乎還是沒辦法完全改過，依舊不能使用對方領地內的物品
其他部分:紅石機關的延遲，紅石機關連閃有朋友跟我說延遲很大，我反覆測試了很多差件，只有大佬你的插件安裝上去之後，紅石連閃不用開中繼器就有延遲了，這部分造成某些紅石機關會失效，雖然大部分紅石機關容易崩服，但還是希望能有個正常的紅石連閃功能，或是能有調整紅石連閃速度的config

**Comment by LazuliKao** [comment]
领地的管理确实存在一点问题，之后会修，
红石刻时长是在配置文件可调的，估计是你改配置文件的时候误开了，配置文件有SlowdownRedstoneTick，三个维度是独立控制的，那个单位是毫秒

**Comment by As12689** [comment]
> 领地的管理确实存在一点问题，之后会修， 红石刻时长是在配置文件可调的，估计是你改配置文件的时候误开了，配置文件有SlowdownRedstoneTick，三个维度是独立控制的，那个单位是毫秒

感謝大佬的教學，目前紅石連閃問題已解決了，期待大佬的1.19.5版更新XD
