### ISSUE TITLE
可否新增功能，禁用普通玩家命令/tell /msg /w等命令使用目标选择器

### ISSUE THREAD

**Issue by rtucc** [LazuliKao/PixelFaramitaLuminousPolymerizationRes#2]
![IMG_20221221_230614](https://user-images.githubusercontent.com/111302703/208940852-4a7b362b-bcb4-4732-b7d1-ed596305c3c6.jpg)
原来的PFEssentials已经有此功能，希望能将其加入ToDo并移植过来，毕竟是一个可以防普通玩家滥用此功能进行恶意刷屏

**Comment by LazuliKao** [comment]
可

**Comment by LazuliKao** [comment]
功能已添加
